import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Providers from './providers'

import Provider from './_trpc/Provider'
import Script from 'next/script'
import dynamic from 'next/dynamic'
import Header from './_components/organisms/header'

const UserSaver = dynamic(() => import('./_components/UserSaver'), {
    ssr: false,
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Onton',
    description: 'Generated by create next app',
    viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
}



export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <Script src="https://telegram.org/js/telegram-web-app.js"></Script>
            <body className={inter.className}>
                <Provider>
                    <Providers>
                        <UserSaver>
                            {/* <WebAppInitialization> */}

                            <main className="p-4">
                                <Header />
                                {children}
                            </main>
                            {/* </WebAppInitialization> */}
                        </UserSaver>
                    </Providers>
                </Provider>
            </body>
        </html>
    )
}
