ALTER TYPE api_name_enum ADD VALUE IF NOT EXISTS 'PRIDIPIE_API';
ALTER TYPE task_function_enum ADD VALUE IF NOT EXISTS 'PridipieAUTH';
ALTER TYPE item_type_enum ADD VALUE IF NOT EXISTS 'EVENT_ORGANIZER';
