/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * API status
     * @description API status healthcheck
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Successful operation */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Finds users
     * @description Finds top users in the order of the number of awards received, `is_name_changed` field, `is_telegram_verified` field, the date awards has been received, and, finally, user Id. Only publicly available data is exposed.
     */
    get: TSAPIoperations["findUsers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{username}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Finds a user by username
     * @description Simply returns publicly available user data
     */
    get: TSAPIoperations["findUserByUsername"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{username}/rank": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Finds a rank of the user
     * @description Returns user's rank in the contributors list given user's username
     */
    get: TSAPIoperations["findUserRankByUsername"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/{username}/sbts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Finds SBTs owned by a user
     * @description Returns a paginated list of SBTs owned by a user given user's username
     */
    get: TSAPIoperations["findUserNftsByUsername"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/collections/{path}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Finds an SBT collection
     * @description Returns an SBT collection data given its id or friendly address
     */
    get: TSAPIoperations["findCollectionById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/collections/{path}/participants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Finds activity participants
     * @description Returns a list of users (in a random order) participated in the activity related to the SBT collection with the given id or friendly address
     */
    get: TSAPIoperations["findCollectionParticipantsById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/last-activities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Finds last activities made by user, i.e., last recevied awards
     * @description An endpoint that compounds data from Users model, Sbt Tokens model, and Strapi Activties. Last activities are most recent rewards (or SBTs) received by users.
     */
    get: TSAPIoperations["findLastActivities"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/hubs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Finds paginated list of ton-society hubs
     * @description An endpoint that compounds data from Users model, Sbt Tokens model, and Strapi Activties. Last activities are most recent rewards (or SBTs) received by users.
     */
    get: TSAPIoperations["findHubs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/activities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new activity
     * @description An endpoint that allows to create a new activity. See [ton-society events catalouge](https://society.ton.org/activities/active). Newly created activity is not posted on the website right away - it first needs to go through moderation.
     */
    post: TSAPIoperations["createEvent"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/activities/{activity_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update an existing activity (earlier created by the same partner id)
     * @description An endpoint that allows to update an activity of the "Events" activity group. See [ton-society events page](https://society.ton.org/activities/events).
     */
    patch: TSAPIoperations["updateEvent"];
    trace?: never;
  };
  "/activities/{activity_id}/rewards": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generates a unique reward link
     * @description Returns a unique reward link for users to receive rewards through particpation in activities. The link is generated based on activity ID, user's unique identificator (wallet friendly address or Telegram user id). For example, users can [connect a wallet](https://docs.ton.org/develop/dapps/ton-connect/overview) before they start participating in the activity. In case of Telegram Mini App, simply use [window.Telegram.WebApp.initData.user.id](https://www.tapps.center/docs/packages/tma-js-init-data/user).
     */
    post: TSAPIoperations["createRewardLink"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/activities/{activity_id}/rewards/{participant_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetch a unique reward link for activity particpants
     * @description Returns a unique reward link using participant's wallet friendly address or Telegram user id. Activity participants can [connect a wallet](https://docs.ton.org/develop/dapps/ton-connect/overview) before they start participating in the activity. In case of Telegram Mini App, simply use [window.Telegram.WebApp.initData.user.id](https://www.tapps.center/docs/packages/tma-js-init-data/user).
     */
    get: TSAPIoperations["findRewardLink"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/activities/{activity_id}/rewards/{participant_id}/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Fetch status of a unique reward link given to a activity particpant
     * @description Returns status of a unique reward link using participant's wallet friendly address or Telegram user id. Activity participants can [connect a wallet](https://docs.ton.org/develop/dapps/ton-connect/overview) before they start participating in the activity. In case of Telegram Mini App, simply use [window.Telegram.WebApp.initData.user.id](https://www.tapps.center/docs/packages/tma-js-init-data/user).
     */
    get: TSAPIoperations["getParticipantRewardStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/csbts/collections/{address}/v1/items/{index}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * For a given collection, returns an item data and the proor cell
     * @description The endpoint follows specifications outlined in the ["Compressed NFT Standard"](https://github.com/krigga/TEPs/blob/compressed-nfts/text/0000-compressed-nft-standard.md#1-itemsindex)
     */
    get: TSAPIoperations["findCsmtItem"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/csbts/collections/{address}/v1/items": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * For a given collection, returns list of item in the slice given its offset and count
     * @description The endpoint follows specifications outlined in the ["Compressed NFT Standard"](https://github.com/krigga/TEPs/blob/compressed-nfts/text/0000-compressed-nft-standard.md#2-itemsoffsetoffsetcountcount)
     */
    get: TSAPIoperations["findCsbtItems"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/csbts/collections/{address}/v1/state": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Returns the state of a compressed SBT collection
     * @description The endpoint follows specifications outlined in the ["Compressed NFT Standard"](https://github.com/krigga/TEPs/blob/compressed-nfts/text/0000-compressed-nft-standard.md#3-state)
     */
    get: TSAPIoperations["findCsbtCollectionState"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PublicUser: {
      /**
       * Format: int64
       * @example 10
       */
      id?: number;
      /** @example Priscilla Miller */
      name?: string;
      /** @example 238497403a24c */
      username?: string;
      /** @example 23 y.o. designer from San-Francisco */
      bio?: string;
      /** @example 166 */
      awards_count?: number;
      /** @example 1711013388 */
      last_award_at?: number;
      /** @example 1711013388 */
      created_at?: number;
      /** @example 1711013388 */
      updated_at?: number;
      /**
       * Format: url
       * @example https://storage.googleapis.com/ton-strapi/Avatar_1321317640_92f4adfc3f/Avatar_1321317640_92f4adfc3f.png
       */
      avatar_url?: string;
    };
    SuccessPublicUser: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: {
        user?: components["schemas"]["PublicUser"];
      };
    };
    SuccessPublicUsers: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: {
        /**
         * Format: int64
         * @example 324
         */
        count?: number;
        users?: components["schemas"]["PublicUser"][];
      };
    };
    Sbt: {
      /**
       * Format: int64
       * @example 10
       */
      id?: number;
      /**
       * Format: int64
       * @example 21
       */
      sbt_collections_id?: number;
      content_uri?: string;
      /** @example TON Bounty */
      name?: string;
      /** @example Reward for valuable TON Ecosystem contributions */
      description?: string;
      /** @example https://tonsociety.s3.eu-central-2.amazonaws.com/596c2c53-deb2-4afd-9318-3d01238ce7c0.png */
      image?: string;
      content_json?: Record<string, never>;
      /**
       * Format: int64
       * @example 1711095609
       */
      created_at?: number;
      /**
       * Format: int64
       * @example 1711095609
       */
      updated_at?: number;
      /** @example EQBAJCGblueX9Nwr84TmrcLmIoPbeunnujBoziT3MtJuaJ0J */
      sbt_collection_address?: string;
    };
    SuccessSbts: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: {
        /**
         * Format: int64
         * @example 18
         */
        count?: number;
        sbts?: components["schemas"]["Sbt"][];
      };
    };
    Collection: {
      /**
       * Format: int64
       * @example 128
       */
      id?: number;
      /** @example 0:4024219B96E797F4DC2BF384E6ADC2E62283DB7AE9E7BA3068CE24F732D26E68 */
      raw_address?: string;
      /** @example EQBAJCGblueX9Nwr84TmrcLmIoPbeunnujBoziT3MtJuaJ0J */
      friendly_address?: string;
      /**
       * Format: int64
       * @example 151
       */
      next_item_index?: number;
      /** @example https://sbt-bot-minter.s3.amazonaws.com//collection.json */
      content_uri?: string;
      /** @example 0:C290189A787E15FBA30142A3250B70F3019F8C8553E9A5E1BAF65723AA3C6C47 */
      raw_owner_address?: string;
      /** @example UQDCkBiaeH4V-6MBQqMlC3DzAZ-MhVPppeG69lcjqjxsR13R */
      friendly_owner_address?: string;
      /** @example TON Bounties Contributors */
      name?: string;
      /** @example TON Bounties program is an open community initiative that is fast-forwarding support for valuable contributions enhancing The Open Network Ecosystem */
      description?: string;
      /** @example https://tonsociety.s3.eu-central-2.amazonaws.com/596c2c53-deb2-4afd-9318-3d01238ce7c0.png */
      image?: string;
      content_json?: Record<string, never>;
      /**
       * Format: int64
       * @example 1711095609
       */
      created_at?: number;
      /**
       * Format: int64
       * @example 1711095609
       */
      updated_at?: number;
      /**
       * Format: int64
       * @example 1
       */
      version?: number;
    };
    SuccessCollection: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: {
        /**
         * Format: int64
         * @example 324
         */
        count?: number;
        users?: components["schemas"]["Collection"][];
      };
    };
    SuccessCollectionParticipants: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: {
        collection?: components["schemas"]["Collection"];
        /**
         * Format: int64
         * @example 69
         */
        count?: number;
        participants?: components["schemas"]["PublicUser"][];
      };
    };
    SuccessLastActivities: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: {
        /**
         * Format: int64
         * @example 68075
         */
        count?: number;
        data?: {
          /** @description Strapi entity */
          activity?: Record<string, never>;
          award?: {
            /** Format: int64 */
            created_at?: number;
            description?: string;
            image?: string;
          };
          user?: components["schemas"]["PublicUser"];
        }[];
      };
    };
    Hub: {
      /**
       * Format: int64
       * @example 1
       */
      id?: number;
      attributes?: {
        /** @example Global */
        title?: string;
        /** @example https://t.me/tonsociety_chat */
        url?: string;
      };
    };
    SuccessHubs: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: components["schemas"]["Hub"][];
    };
    SuccessEventCreation: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: {
        /**
         * @description Unique id of the newly created activity
         * @example 239
         */
        activity_id?: number;
        /**
         * @description Unique society.ton.org url of the newly created activity (the value might change after moderation)
         * @example https://society.ton.org/open-league-summer-taipei-bootcamp
         */
        activity_url?: string;
      };
    };
    EmptySuccess: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: Record<string, never>;
    };
    CsbtItem: {
      metadata?: {
        /**
         * @description Item's owner
         * @example 0:000000000000000000000000000000000000000000000000000000000000000
         */
        owner?: string;
        /**
         * @description Item's individual content
         * @example te6cckEBAQEACAAADDAuanNvbuTiyMU=
         */
        individual_content?: string;
        /** @example TON Bounties Contributors */
        name?: string;
        /** @example TON Bounties program is an open community initiative that is fast-forwarding support for valuable contributions enhancing The Open Network Ecosystem */
        description?: string;
        /** @example https://tonsociety.s3.eu-central-2.amazonaws.com/596c2c53-deb2-4afd-9318-3d01238ce7c0.png */
        image?: string;
      };
      /**
       * @description Item's index
       * @example 0
       */
      index?: string;
    };
    CsbtItemByIndex: {
      item?: components["schemas"]["CsbtItem"];
      /**
       * @description Proof cell that allows one claiming an item on the blockchain
       * @example te6cckEBBgEAeQACAAEDAUOAFa1KqA2Oswxbo4Rgh/q6NEaPLuK9o3fo1TFGn+MySjqQAgAMMi5qc29uAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQBQF4S3GMDJY/HoZd6TCREIOnCaYlF23hNzJaSsfMd1S7nBQAA8muEeQ==
       */
      proof_cell?: string;
    };
    CsbtItems: {
      /** @description if no items exisits in the slice, null values should be returned instead (see the standrad for details) */
      items?: components["schemas"]["CsbtItem"][];
      /**
       * @description Index of the very last item in the collection. This is a part of the collection state.
       * @example 37
       */
      last_index?: string;
    };
    CsbtCollectionState: {
      /**
       * @description Index of the very last item in the collection
       * @example 37
       */
      last_index?: string;
      /**
       * @description The address of the collection smart contract that this API augments
       * @example 0:000000000000000000000000000000000000000000000000000000000000000
       */
      address?: string;
    };
    CreateRewardLinkBody: {
      /**
       * @description The wallet address (in the friendly format), to which a reward is to be issued. Can be left empty if telegram_user_id is provided.
       * @example EQDxnrrz-0kgdjehShvisBy2sX7ATVFgoiFKStnD7D8qihVv
       */
      wallet_address?: string;
      /**
       * Format: int64
       * @description Telegram id associated with an account, to which a reward is to be issued. Can be left empty if wallet_address is provided.
       * @example 439739
       */
      telegram_user_id?: number;
      /**
       * @deprecated
       * @description Attributes that will be displayed for SBT on marketplaces and at user wallets
       */
      attributes?: {
        /** @example Organizer */
        trait_type?: string;
        /** @example TON Society Asia */
        value?: string;
      }[];
      /** @description Item metadata */
      item_metadata?: components["schemas"]["ItemMetadataJson"];
    };
    ItemMetadataJson: {
      /**
       * @description SBT name
       * @example TON Meetup for Developers and Founders
       */
      name?: string;
      /**
       * @description SBT description
       * @example Reward for participation
       */
      description?: string;
      /**
       * @description SBT image URL
       * @example https://tonsociety.s3.eu-central-2.amazonaws.com/418b25e2-b748-4a64-b8d8-f103ed281049.png
       */
      image?: string;
      /**
       * @description URL for an additional content
       * @example https://tonsociety.s3.eu-central-2.amazonaws.com/408f0700-2113-4012-b1ca-8a6aac8ef0fb.mp4
       */
      content_url?: string;
      /**
       * @description Type of content used for SBT display
       * @example video/mp4
       */
      content_type?: string;
      /** @description Buttons to be displayed on SBT */
      buttons?: {
        /** @example https://society.ton.org/welcome */
        uri?: string;
        /** @example View on TON Society */
        label?: string;
      }[];
      /**
       * @description Organizer category
       * @example TON Society Asia
       */
      organizer?: string;
      /**
       * @description Address used to complete the activity
       * @example https://lu.ma/9ovl6qeq
       */
      original_activity_url?: string;
      /**
       * @description Activity start date
       * @example 2024-02-22
       */
      start_date_iso?: string;
      /**
       * @description Activity end date
       * @example 2024-02-22
       */
      end_date_iso?: string;
      /**
       * @description Type of activity
       * @example Hackathon
       */
      activity_type?: string;
      /** @description A set of attributes describing the place where activity happens */
      place?: {
        /** @example Offline */
        type?: string;
        /** @example HK */
        country_code_iso?: string;
        /** @example 22.2793278,114.1628131 */
        place_coordinates_osm?: string;
        /** @example Congress Center */
        venue_name?: string;
      };
      /**
       * @description Any additional data provided by user when completing an activity
       * @example John Doe
       */
      user_data?: string;
      /** @description Attributes that will be displayed for SBT on marketplaces and at user wallets */
      attributes?: {
        /** @example Organizer */
        trait_type?: string;
        /** @example TON Society Asia */
        value?: string;
      }[];
    };
    SuccessRewardLink: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: {
        /** @example https://society.ton.org/welcome/52528543-df85-4529-afbd-07ac7c48187d */
        reward_link?: string;
      };
    };
    RewardsExistingCollection: {
      /** @enum {string} */
      mint_type: "existing_collection";
      /**
       * @description Friendly address of the existing collection
       * @example EQBMKz_q9PNYh25t9LneI0lVI5zEab07Fzn_Z8MBtgEd6l7L
       */
      collection_address: string;
    };
    RewardsManualMint: {
      /** @enum {string} */
      mint_type: "manual";
      collection: components["schemas"]["CollectionTemplate"];
    };
    /** @description If collection data is not provided, the hub's default collection metadata will be used. Otherwise, the fields you provide will overwrite the hub's default collection metadata. */
    RewardsHubBased: {
      /** @enum {string} */
      mint_type: "hub_based";
      /** @description Optional collection template payload to overwrite the Hub's default collection template */
      collection?: components["schemas"]["CollectionTemplate"];
    };
    /** @description Collection metadata. */
    CollectionTemplate: {
      /**
       * @description Title of the collection
       * @example Open League Summer: Taipei Bootcamp
       */
      title?: string;
      /**
       * @description Description of the collection
       * @example Open League Summer is a global hackathon for developers, designers, and enthusiasts to build the future of the Open Network Ecosystem
       */
      description?: string;
      /** @description Image of the collection */
      image?: {
        /**
         * @description URL of the image
         * @example https://tonsociety.s3.eu-central-2.amazonaws.com/596c2c53-deb2-4afd-9318-3d01238ce7c0.png
         */
        url?: string;
      };
      /** @description Cover image of the collection */
      cover?: {
        /**
         * @description URL of the cover image
         * @example https://tonsociety.s3.eu-central-2.amazonaws.com/e508ec26-2b3a-456f-b53b-55b9f4de1e4e.png
         */
        url?: string;
      };
      /** @description Metadata of the collection */
      metadata?: {
        /** @description Social links of the collection */
        social_links?: string[];
      };
      /**
       * @description Item title of the collection
       * @example Open League Summer: Taipei Bootcamp
       */
      item_title?: string;
      /**
       * @description Item description of the collection
       * @example Reward for participation
       */
      item_description?: string;
      /** @description Item image of the collection */
      item_image?: {
        /**
         * @description URL of the item image
         * @example https://tonsociety.s3.eu-central-2.amazonaws.com/596c2c53-deb2-4afd-9318-3d01238ce7c0.png
         */
        url?: string;
      };
      /** @description Item video of the collection. In case of `hub-based` mint type, pass `null` value explicitly if you don't want to add video to the collection. Otherwise, the video from hub's collection template will be used. */
      item_video?: {
        /**
         * @description URL of the item video
         * @example https://tonsociety.s3.eu-central-2.amazonaws.com/408f0700-2113-4012-b1ca-8a6aac8ef0fb.mp4
         */
        url?: string;
      };
      /** @description Item metadata of the collection */
      item_metadata?: {
        /** @description Buttons displayed at marketplaces and user wallets */
        buttons?: {
          /**
           * @description Uri of the collection item button
           * @example https://lu.ma/3mx6a7l7
           */
          uri?: string;
          /**
           * @description Label of the collection item button
           * @example Open in TON Society
           */
          label?: string;
        }[];
        /**
         * @description Type of the activity
         * @example Event
         */
        activity_type?: string;
        /**
         * @description Organizer category
         * @example Community
         */
        organizer?: string;
        /**
         * @description Address used to complete the activity
         * @example https://lu.ma/9ovl6qeq
         */
        original_activity_url?: string;
        /**
         * @description Activity start date in ISO 8601 format
         * @example 2024-01-22
         */
        start_date_iso?: string;
        /**
         * @description Activity end date in ISO 8601 format
         * @example 2024-01-22
         */
        end_date_iso?: string;
        /** @description A set of attributes describing the place where activity happens */
        place?: {
          /**
           * @description Use Online for online events or Offline for offline events
           * @example Online
           */
          type?: string;
          /**
           * @description If type is Offline, specify two-letter country code from ISO 3166-1
           * @example US
           */
          country_code_iso?: string;
          /**
           * @description If type is Offline, specify place coordinates (lat, lon).
           * @example 47.6062095,-122.3320708
           */
          place_coordinates_osm?: string;
          /**
           * @description If type is Offline, specify venue name
           * @example Congress Hall
           */
          venue_name?: string;
        };
        /**
         * @description Any additional data provided by user when completing an activity
         * @example TON Society Taipei
         */
        user_data?: string;
        /** @description Attributes that will be displayed for SBT on marketplaces and at user wallets */
        attributes?: {
          /**
           * @description Trait type of the collection item attribute
           * @example Strength
           */
          trait_type?: string;
          /**
           * @description Value of the collection item attribute
           * @example 99
           */
          value?: string;
        }[];
      };
    };
    SuccessRewardLinkStatus: {
      /**
       * @example success
       * @enum {string}
       */
      status?: "success" | "error" | "fail";
      data?: {
        /**
         * @description Indicates the status of the reward link.
         *     Possible values:
         *     - `NOT_CLAIMED`: The reward has not been claimed by the participant.
         *     - `CLAIMED`: The reward has been claimed by the participant.
         *     - `MINTED`: The reward has been minted on the society.ton.org side.
         *     - `RECEIVED`: The reward has been received by the participant and visible in the society.ton.org profile.
         *
         * @example NOT_CLAIMED
         * @enum {string}
         */
        status?: "NOT_CLAIMED" | "CLAIMED" | "MINTED" | "RECEIVED";
      };
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface TSAPIoperations {
  findUsers: {
    parameters: {
      query: {
        /** @description Paginated list start index */
        _start: number;
        /** @description Paginated list end index */
        _end: number;
        /** @description Filters users who own an SBT in the given collection. Collection ids are usually provided in the `api::activity` Strapi entity. */
        collection_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessPublicUsers"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findUserByUsername: {
    parameters: {
      query?: {
        /** @description Returns user data only if this user owns an SBT in the collection with the provided id. */
        collection_id?: number;
      };
      header?: never;
      path: {
        /** @description User's username */
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessPublicUser"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findUserRankByUsername: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description User's username */
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /**
             * @example success
             * @enum {string}
             */
            status?: "success" | "error" | "fail";
            /**
             * Format: int64
             * @example 112
             */
            data?: number;
          };
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findUserNftsByUsername: {
    parameters: {
      query: {
        /** @description Paginated list start index */
        _start: number;
        /** @description Paginated list end index */
        _end: number;
      };
      header?: never;
      path: {
        /** @description User's username */
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessSbts"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findCollectionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description SBT collection id or friendly address */
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessCollection"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findCollectionParticipantsById: {
    parameters: {
      query: {
        /** @description The maximum number of participants to return */
        limit: number;
      };
      header?: never;
      path: {
        /** @description SBT collection id or friendly address */
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessCollectionParticipants"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findLastActivities: {
    parameters: {
      query: {
        /** @description Paginated list start index */
        _start: number;
        /** @description Paginated list end index */
        _end: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessLastActivities"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findHubs: {
    parameters: {
      query: {
        /** @description Paginated list start index */
        _start: number;
        /** @description Paginated list end index */
        _end: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessHubs"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createEvent: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /**
           * @description The activity title
           * @example Open League Summer: Taipei Bootcamp
           */
          title: string;
          /**
           * @description The activity subtitle
           * @example $2,000,000 in prizes and 13 IRL Bootcamps!
           */
          subtitle: string;
          /**
           * @description The activity description
           * @example **Meet Open League Summer Bootcamp in Taipei!**
           *     PITCH. BUILD. GROW. WIN.
           *     **$2,000,000** in prizes and 13 IRL Bootcamp events — this is The Open League Summer 🔥
           *     It’s going to be hot and exciting!
           */
          description: string;
          /**
           * @description Id of the corresponding ton-society hub of the activity (e.g., CIS, Global, etc.). Use [/hubs](https://society.ton.org/v1/hubs?_start=0&_end=3) endpoint to retrieve the list of hubs.
           * @example 1
           */
          hub_id: number;
          /**
           * @description The activity additional information
           * @example Taipei, Taiwan
           */
          additional_info?: string;
          /**
           * @description The start date of the activity in the appropriate format
           * @example 2024-05-31
           */
          start_date?: string;
          /**
           * @description The end date of the activity in the appropriate format
           * @example 2024-06-02
           */
          end_date?: string;
          cta_button?: {
            /**
             * @description Label shown on the CTA button
             * @example Event details
             */
            label: string;
            /**
             * @description External link opened when the CTA button is clicked
             * @example https://lu.ma/3mx6a7l7
             */
            link: string;
          };
          rewards?:
            | components["schemas"]["RewardsManualMint"]
            | components["schemas"]["RewardsExistingCollection"]
            | components["schemas"]["RewardsHubBased"];
        };
      };
    };
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessEventCreation"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateEvent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of the activity to be patched */
        activity_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /**
           * @description The activity title
           * @example Open League Summer: Taipei Bootcamp
           */
          title?: string;
          /**
           * @description The activity subtitle
           * @example $2,000,000 in prizes and 13 IRL Bootcamps!
           */
          subtitle?: string;
          /**
           * @description The activity description
           * @example **Meet Open League Summer Bootcamp in Taipei!**
           *     PITCH. BUILD. GROW. WIN.
           *     **$2,000,000** in prizes and 13 IRL Bootcamp events — this is The Open League Summer 🔥
           *     It’s going to be hot and exciting!
           */
          description?: string;
          /**
           * @description Id of the corresponding ton-society hub of the activity (e.g., CIS, Global, etc.). Use [/hubs](https://society.ton.org/v1/hubs?_start=0&_end=3) endpoint to retrieve the list of hubs.
           * @example 1
           */
          hub_id?: number;
          /**
           * @description The activity additional information
           * @example Taipei, Taiwan
           */
          additional_info?: string;
          /**
           * @description The start date of the activity in the appropriate format. To nullify pass "null"
           * @example 2024-05-31
           */
          start_date?: string;
          /**
           * @description The end date of the activity in the appropriate format. To nullify pass "null"
           * @example 2024-06-02
           */
          end_date?: string;
          cta_button?: {
            /**
             * @description Label shown on the CTA button
             * @example Event details
             */
            label?: string;
            /**
             * @description External link opened when the CTA button is clicked
             * @example https://lu.ma/3mx6a7l7
             */
            link?: string;
          };
        };
      };
    };
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EmptySuccess"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  createRewardLink: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Activity id */
        activity_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateRewardLinkBody"];
      };
    };
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessRewardLink"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findRewardLink: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of the activity, for wich the participant was rewarded */
        activity_id: number;
        /** @description Unique identifier of the activity participant, either wallet address (friendly format) or Telegram user Id */
        participant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessRewardLink"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getParticipantRewardStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Id of the activity, for wich the participant was rewarded */
        activity_id: number;
        /** @description Unique identifier of the activity participant, either wallet address (friendly format) or Telegram user Id */
        participant_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SuccessRewardLinkStatus"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found. There is no such combination of the activity id and participant data */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findCsmtItem: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description SBT collection friendly address */
        address: string;
        /** @description Index of the requested item */
        index: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CsbtItemByIndex"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findCsbtItems: {
    parameters: {
      query: {
        /** @description Starting index of the returned slice of items */
        offset: number;
        /** @description Number of items to return */
        count: number;
      };
      header?: never;
      path: {
        /** @description SBT collection friendly address */
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CsbtItems"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  findCsbtCollectionState: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description SBT collection friendly address */
        address: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CsbtCollectionState"];
        };
      };
      /** @description Invalid query/path/body param provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Resource not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Internal server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}

export type TONSOcietyAPISchemaT = components["schemas"];


export type findActivityResponseType = {
  data: {
    additional_info: string;
    description: string;
    end_date: string;
    join_button: {
      link: string;
      title: string;
    };
    link: string;
    public_path: string;
    publishedAt: string;
    rewards: {
      collection: {
        cover: {
          url: string;
        };
        description: string;
        image: {
          url: string;
        };
        item_description: string;
        item_image: {
          url: string;
        };
        item_metadata: {
          activity_type: string;
          attributes: {
            trait_type: string;
            value: string;
          }[];
          buttons: {
            label: string;
            uri: string;
          }[];
          content_type: string;
          content_url: string;
          description: string;
          end_date_iso: string;
          image: string;
          name: string;
          organizer: string;
          original_activity_url: string;
          place: {
            country_code_iso: string;
            place_coordinates_osm: string;
            type: string;
            venue_name: string;
          };
          start_date_iso: string;
          user_data: string;
        };
        item_title: string;
        item_video: {
          file: {
            url: string;
          };
          present: boolean;
        };
        metadata: {
          cover_image: string;
          description: string;
          image: string;
          name: string;
          social_links: string[];
        };
        title: string;
      };
      collection_address: string;
      hub: {
        id: number;
      };
      mint_type: string;
    };
    start_date: string;
    subtitle: string;
    title: string;
  };
  status: "success";
};
